import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const inter = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Ai-Mecca Touring",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="m-0 p-0 ">
      <body className={`${inter.className} h-screen w-screen `}>{children}</body>
    </html>
  );
}
